name: semantic-versioning-maven
description: >
  A simple GitHub Action to increment the Maven version of a project based on conventional commits.
author: Richard Innocent

inputs:
  access-token:
    description: >
      The token used to perform the commit actions such as committing the version changes to the
      repository. If unset, the default token for your action will be used.
    required: false
  git-email:
    description: The email address each commit will be associated with.
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-username:
    description: The GitHub username each commit will be associated with.
    required: false
    default: github-actions[bot]
  pom-path:
    description: >
      The path within your directory where the parent pom.xml you intend to change is located.
    required: false
    default: .
  version-prefix:
    description: The prefix to include before the semantic version number.
    required: false
    default: v

outputs:
  previous-version:
    description: >
      The version before the version was incremented. This may be the same as the new version.
    value: ${{ steps.increment-version.outputs.previous-version }}
  new-version:
    description: >
      The new version after the version was incremented. This may be the same as the previous
      version.
    value: ${{ steps.increment-version.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - name: Print action path
      run: echo "${GITHUB_ACTION_PATH}"
      shell: bash
    - name: Increment version
      id: increment-version
      run: ${GITHUB_ACTION_PATH}/update_version.sh
      shell: bash
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        GIT_EMAIL: ${{ inputs.git-email }}
        GIT_USERNAME: ${{ inputs.git-username }}
        POM_PATH: ${{ inputs.pom-path }}
        VERSION_PREFIX: ${{ inputs.version-prefix }}
    - name: Print outputs
      run: echo "Updated version. $PREVIOUS_VERSION -> $NEW_VERSION"
      shell: bash
      env:
        PREVIOUS_VERSION: ${{ steps.increment-version.outputs.previous-version }}
        NEW_VERSION: ${{ steps.increment-version.outputs.new-version }}

branding:
  color: orange
  icon: arrow-up-circle
