name: semantic-versioning-maven
description: >
  A simple GitHub Action to increment the Maven version of a project based on conventional commits.
author: Richard Innocent

inputs:
  token:
    description: >
      The token used to perform the commit actions such as committing the version changes to the
      repository.
    required: true
  gitEmail:
    description: The email address each commit will be associated with.
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
  gitUsername:
    description: The GitHub username each commit will be associated with.
    required: false
    default: github-actions[bot]
  pomPath:
    description: >
      The path within your directory where the parent pom.xml you intend to change is located.
    required: false
    default: .

outputs:
  previousVersion:
    description: >
      The version before the version was incremented. This may be the same as the new version.
  newVersion:
    description: >
      The new version after the version was incremented. This may be the same as the previous
      version.

runs:
  using: "composite"
  steps:
    - name: Increment version and deploy
      run: ${{ github.action_path }}/update_version.sh
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        GIT_EMAIL: ${{ inputs.gitEmail }}
        GIT_USERNAME: ${{ inputs.gitUsername }}
        POM_PATH: ${{ inputs.pomPath }}

branding:
  color: orange
  icon: arrow-up-circle
