name: semantic-versioning-maven
description: >
  A simple GitHub Action to increment the Maven version of a project based on conventional commits.
author: Richard Innocent

inputs:
  token:
    description: >
      The token used to perform the commit actions such as committing the version changes to the
      repository.
    required: true
  git-email:
    description: The email address each commit will be associated with.
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-username:
    description: The GitHub username each commit will be associated with.
    required: false
    default: github-actions[bot]
  pom-path:
    description: >
      The path within your directory where the parent pom.xml you intend to change is located.
    required: false
    default: .

outputs:
  previous-version:
    description: >
      The version before the version was incremented. This may be the same as the new version.
    value: ${{ steps.increment-version.outputs.previous-version }}
  new-version:
    description: >
      The new version after the version was incremented. This may be the same as the previous
      version.
    value: ${{ steps.increment-version.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - name: Find update_version.sh
      run: find /home -name update_version.sh
      shell: bash
    - name: Increment version
      id: increment-version
      run: ${{ github.action_path }}/update_version.sh
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        GIT_EMAIL: ${{ inputs.git-email }}
        GIT_USERNAME: ${{ inputs.git-username }}
        POM_PATH: ${{ inputs.pom-path }}
    - name: Print outputs
      run: echo "Updated version. $PREVIOUS_VERSION -> $NEW_VERSION"
      shell: bash
      env:
        PREVIOUS_VERSION: ${{ steps.increment-version.outputs.previous-version }}
        NEW_VERSION: ${{ steps.increment-version.outputs.new-version }}

branding:
  color: orange
  icon: arrow-up-circle
